#ifndef TEST1_APP_CONFIG_H
#define TEST1_APP_CONFIG_H

/* Physical wheel mapping: ID1=FL, ID2=FR, ID3=RL, ID4=RR. */
#define USER_VERIFY_MOTOR_FL_BASE_ID 1U
#define USER_VERIFY_MOTOR_FR_BASE_ID 2U
#define USER_VERIFY_MOTOR_RL_BASE_ID 3U
#define USER_VERIFY_MOTOR_RR_BASE_ID 4U

#define DM_VELOCITY_COMMAND_ID_OFFSET 0x200U
#define FDCAN_KERNEL_CLOCK_HZ 80000000UL
#define FDCAN_NOMINAL_BITRATE_HZ 1000000UL
#define FDCAN_NOM_PRESCALER 1U
#define FDCAN_NOM_SJW 20U
#define FDCAN_NOM_SEG1 59U
#define FDCAN_NOM_SEG2 20U

/* Chassis parameters copied from the previous project; verify on the real car. */
#define WHEEL_RADIUS_M 0.050f
#define CHASSIS_HALF_LENGTH_M 0.180f
#define CHASSIS_HALF_WIDTH_M 0.160f
#define MOTOR_MAX_WHEEL_RAD_S 58.6431f
/* Scales decoded DM feedback velocity to wheel-end rad/s; calibrated from route logs. */
#define MOTOR_FEEDBACK_WHEEL_SPEED_SCALE 3.55f
/* Keep the odometry loop closed, but tolerate one delayed feedback frame. */
#define MOTOR_FEEDBACK_STALE_TIMEOUT_MS 500U
#define MOTOR_FEEDBACK_MIN_VALID_COUNT 3U
#define WHEEL_FL_SIGN 1.0f
#define WHEEL_FR_SIGN -1.0f
#define WHEEL_RL_SIGN 1.0f
#define WHEEL_RR_SIGN -1.0f

/* Autonomous route: enter the disc station with the mirrored cubic arc
 * (forward endpoint 3.93 m, lateral endpoint 0.65 m), perform DISC_CATCH,
 * then take one diagonal task-two entry of 1.35 m backward and 2.25 m toward
 * the selected field side while rotating 172 degrees, and run eight slots.
 * The platform task first locks two distinct A/B/C/D letters with the
 * secondary camera, then uses the main camera for all eight slots. */
#define CONTROL_PERIOD_MS 10U
#define ROUTE_AUTO_RUN_ON_BOOT 1U
/* PA5/ADC1_INP19 is the LCD joystick ladder.  Only RIGHT/DOWN may start a
 * route: RIGHT selects RED and DOWN selects BLUE. */
#define ROUTE_WAIT_USER_KEY_ON_BOOT 1U
#define ROUTE_USER_KEY_DEBOUNCE_MS 50U
#define LCD_JOYSTICK_ADC_MAX_RAW 4095UL
#define LCD_JOYSTICK_PRESS_MAX_RAW 200UL
#define LCD_JOYSTICK_RIGHT_MIN_RAW 700UL
#define LCD_JOYSTICK_RIGHT_MAX_RAW 1000UL
#define LCD_JOYSTICK_LEFT_MIN_RAW 1500UL
#define LCD_JOYSTICK_LEFT_MAX_RAW 1800UL
#define LCD_JOYSTICK_UP_MIN_RAW 2200UL
#define LCD_JOYSTICK_UP_MAX_RAW 2500UL
#define LCD_JOYSTICK_DOWN_MIN_RAW 2800UL
#define LCD_JOYSTICK_DOWN_MAX_RAW 3500UL
#define LCD_JOYSTICK_MEDIAN_SAMPLES 3U
#define ROUTE_POWER_ON_SETTLE_MS 50U
/* Start the chassis route immediately. RK synchronization runs in the
 * background until the first arm station is reached. */
#define ROUTE_WAIT_RK_READY_ON_BOOT 1U
#define RK_ARM_BOOT_READY_TIMEOUT_MS 2500U
#define RK_ARM_PRETASK_SYNC_PERIOD_MS 250U
#define RK_ARM_RESET_BEFORE_ROUTE_TIMEOUT_MS 3500U
#define CAN_STARTUP_RETRY_TIMEOUT_MS 5000U
#define CAN_STARTUP_RETRY_GAP_MS 50U
/* Airborne integration mode: keep the route state machine running even if
 * motor CAN startup/feedback is late. Restore these to 1 before ground runs. */

#define ROUTE_REQUIRE_CAN_STARTUP 1U

#define ROUTE_REQUIRE_MOTOR_ENABLE 1U

#define ROUTE_REQUIRE_MOTOR_FEEDBACK 1U

#define ROUTE_REQUIRE_MOTOR_TX_SUCCESS 1U

#define ROUTE_STRAFE_DISTANCE_M 0.530f
#define ROUTE_FORWARD_DISTANCE_M 3.930f
#define ROUTE_DISC_ARC_ENTRY_ENABLED 1U
/* Cubic entry shaped like the field sketch: acquire most of the lateral
 * offset early, then run almost straight into the disc marker.  The final
 * endpoint remains ROUTE_FORWARD_DISTANCE_M / ROUTE_STRAFE_DISTANCE_M. */
#define ROUTE_DISC_ARC_CONTROL1_FORWARD_M 0.150f
#define ROUTE_DISC_ARC_CONTROL1_LATERAL_M 0.083571f
#define ROUTE_DISC_ARC_CONTROL2_FORWARD_M 0.550f
#define ROUTE_DISC_ARC_CONTROL2_LATERAL_M 0.626786f
#define ROUTE_DISC_ARC_MAX_SPEED_M_S 1.400f
#define ROUTE_DISC_ARC_ACCEL_M_S2 0.500f
#define ROUTE_DISC_ARC_TIMEOUT_MS 9000U
#define ROUTE_DISC_ARC_ENDPOINT_CAPTURE_U 0.850f
#define ROUTE_DISC_ARC_ENDPOINT_KP 1.20f
#define ROUTE_DISC_ARC_ENDPOINT_MAX_SPEED_M_S 0.450f
#define ROUTE_DISC_ARC_ENDPOINT_MIN_SPEED_M_S 0.120f
#define ROUTE_DISC_ARC_ENDPOINT_TOLERANCE_M 0.030f
#define ROUTE_DISC_ARC_DONE_DISTANCE_TOLERANCE_M 0.080f
#define ROUTE_DISC_ARC_DONE_FORWARD_TOLERANCE_M 0.030f
#define ROUTE_DISC_ARC_DONE_FORWARD_OVERSHOOT_TOLERANCE_M 0.050f
#define ROUTE_DISC_ARC_DONE_PROGRESS_MIN 0.980f
#define ROUTE_DISC_ARC_DONE_SPEED_TOLERANCE_M_S 0.080f
#define ROUTE_DISC_ARC_DONE_HEADING_TOLERANCE_RAD 0.060f
#define ROUTE_DISC_ARC_ODOM_FORWARD_SCALE 0.880f
#define ROUTE_DISC_ARC_ODOM_LATERAL_SCALE 1.450f
#define ROUTE_DISC_PREP_RETRY_PERIOD_MS 300U
#define ROUTE_DISC_PREP_HIGH_ID1_TICK 600
#define ROUTE_DISC_PREP_HIGH_ID2_TICK 600
#define ROUTE_DISC_PREP_HIGH_ID6_TICK 650
/* Camera reference measured at the desired DISC station pose, 800x600.
 * Formal task one uses the main-camera white-line closed loop after the arc.
 * The RK detector reports Y10 in tenths of a pixel. */
#define ROUTE_DISC_VISUAL_ALIGN_ENABLED 1U
#define ROUTE_DISC_LINE_FRAME_WIDTH 800
#define ROUTE_DISC_LINE_FRAME_HEIGHT 600
#define ROUTE_DISC_LINE_REFERENCE_Y10 3150
#define ROUTE_DISC_LINE_REFERENCE_TOLERANCE_Y10 100L
#define ROUTE_DISC_LINE_REFERENCE_A100 0
#define ROUTE_DISC_LINE_FORWARD_SPEED_M_S 0.080f
#define ROUTE_DISC_LINE_ACCEL_M_S2 0.100f
#define ROUTE_DISC_LINE_ANGLE_DEADBAND_DEG 1.5f
#define ROUTE_DISC_LINE_ANGLE_ALIGN_TOLERANCE_DEG 2.5f
#define ROUTE_DISC_LINE_ANGLE_STABLE_SAMPLES 3U
#define ROUTE_DISC_LINE_Y10_FILTER_SAMPLES 3U
#define ROUTE_DISC_LINE_REFERENCE_STABLE_SAMPLES 1U
#define ROUTE_DISC_LINE_Y10_MAX_JUMP 1800L
#define ROUTE_DISC_LINE_TURN_KP_RAD_S_PER_DEG 0.040f
#define ROUTE_DISC_LINE_TURN_KD 0.08f
#define ROUTE_DISC_LINE_MAX_TURN_RAD_S 0.18f
#define ROUTE_DISC_LINE_QUERY_PERIOD_MS 40U
#define ROUTE_DISC_LINE_STALE_MS 350U
#define ROUTE_DISC_LINE_TIMEOUT_MS 60000U
#define ROUTE_DISC_LINE_REVERSE_SEARCH_MS 900U
#define ROUTE_DISC_LINE_FALLBACK_FORWARD_M 0.000f
#define ROUTE_DISC_LINE_AFTER_CROSSED_FORWARD_M 0.070f
#define ROUTE_DISC_LINE_BYPASS_FORWARD_M 0.0255f
/* Standalone task-two starts at the task-two area, first translates laterally
 * to the platform line, then approaches the main-camera white-line reference
 * at a deliberately slow speed. After reaching the reference, the standalone
 * test makes one fixed 170 mm forward approach and then stops white-line
 * tracking. Keep these values separate from the formal task-one route above. */
#define ROUTE_TASK2_TEST_INITIAL_LATERAL_M 0.400f
#define ROUTE_TASK2_TEST_INITIAL_TRANSLATION_SPEED_M_S 0.200f
#define ROUTE_TASK2_TEST_TRANSLATION_SPEED_M_S 0.500f
#define ROUTE_TASK2_TEST_WHITE_LINE_REFERENCE_Y10 2000L
#define ROUTE_TASK2_TEST_WHITE_LINE_REFERENCE_TOLERANCE_Y10 100L
#define ROUTE_TASK2_TEST_WHITE_LINE_FORWARD_SPEED_M_S 0.100f
#define ROUTE_TASK2_TEST_WHITE_LINE_ACCEL_M_S2 0.100f
#define ROUTE_TASK2_TEST_WHITE_LINE_AFTER_CROSSED_FORWARD_M 0.170f
#define ROUTE_TASK2_ENTRY_BACKWARD_COMPONENT_M 1.350f
#define ROUTE_TASK2_ENTRY_LATERAL_COMPONENT_M 2.120f
#define ROUTE_TASK2_ENTRY_DIAGONAL_DISTANCE_M 2.5133444f
#define ROUTE_TASK2_ENTRY_TURN_ANGLE_RAD 3.0019663f /* 172 deg */
#define ROUTE_AFTER_PLATFORM_REVERSE_COMPONENT_M 0.950f
#define ROUTE_AFTER_PLATFORM_LEFT_COMPONENT_M 0.000f
#define ROUTE_AFTER_PLATFORM_DIAGONAL_DISTANCE_M 0.9500000f
#define ROUTE_FRONT_CENTER_ORBIT_RADIUS_M 0.450f
#define ROUTE_FRONT_CENTER_ORBIT_ANGLE_RAD 4.7123890f
#define ROUTE_FRONT_CENTER_ORBIT_TIMEOUT_MS 12000U
#define ROUTE_ORBIT_MAX_SPEED_RAD_S 1.000f
#define ROUTE_ORBIT_ACCEL_RAD_S2 1.800f
#define ROUTE_ORBIT_KP 1.80f
#define ROUTE_ORBIT_KD 0.25f
#define ROUTE_TASK3_TEST_ORBIT_RADIUS_MM 400U
#define ROUTE_TASK3_TEST_ORBIT_RADIUS_M 0.400f
#define ROUTE_TASK3_TEST_ORBIT_ANGLE_DEG 360U
#define ROUTE_TASK3_TEST_ORBIT_ANGLE_RAD 6.2831853f
#define ROUTE_FORMAL_TASK3_ORBIT_ANGLE_DEG 360U
#define ROUTE_FORMAL_TASK3_ORBIT_ANGLE_RAD 6.2831853f
#define ROUTE_FORMAL_TASK3_ORBIT_TIMEOUT_MS 120000U
#define ROUTE_FORMAL_TASK3_ORBIT_MAX_SPEED_RAD_S 0.200f
#define ROUTE_FORMAL_TASK3_ORBIT_ACCEL_RAD_S2 0.600f
#define ROUTE_TASK3_TEST_ORBIT_TIMEOUT_MS 120000U
#define ROUTE_TASK3_TEST_ORBIT_MAX_SPEED_RAD_S 0.200f
#define ROUTE_TASK3_TEST_ORBIT_ACCEL_RAD_S2 0.600f
#define ROUTE_TASK3_TEST_ORBIT_SLOW_SPEED_RAD_S 0.080f
#define ROUTE_TASK3_TEST_ORBIT_SPEED_RAMP_RAD_S2 0.500f
#define ROUTE_TASK3_TEST_STATUS_RETRY_MS 250U
#define ROUTE_FINAL_REVERSE_DISTANCE_M 0.300f
#define ROUTE_TASK3_POST_REVERSE_DISTANCE_M 0.720f
#define ROUTE_POST_ROUTE_LEFT_SHIFT_DISTANCE_M 0.300f
#define ROUTE_POST_ROUTE_FINAL_LEFT_SHIFT_DISTANCE_M 1.000f
#define ROUTE_POST_ROUTE_FINAL_FORWARD_DISTANCE_M 0.500f
#define ROUTE_TASK3_POST_RED_LEFT_SHIFT_DISTANCE_M 0.300f
#define ROUTE_TASK3_POST_AUX_HOLD_MS 5000U
#define ROUTE_SERVO_OPEN_HOLD_MS 2000U
#define ROUTE_SERVO_RETURN_SETTLE_MS 700U
#define ROUTE_SERVO_INITIAL_ANGLE_DEG 0.0f

/* The two end-of-route SG90 units are connected to the ZL ZP20S 24-channel
 * bus board, not to the H7 local PWM outputs.  Keep their fixed pulse values
 * explicit for the whole run: S12 holds 600 and S23 holds 1000. */
#define ROUTE_AUX_ZP_S12_CHANNEL 12U
#define ROUTE_AUX_ZP_S23_CHANNEL 23U
#define ROUTE_AUX_ZP_S12_PULSE 600U
#define ROUTE_AUX_ZP_S23_PULSE 1000U
#define ROUTE_TASK3_POST_S23_PULSE 500U
#define ROUTE_TASK3_POST_S23_RESTORE_PULSE ROUTE_AUX_ZP_S23_PULSE
#define ROUTE_TASK3_POST_S12_PULSE 1200U
#define ROUTE_TASK3_POST_S12_RESTORE_PULSE ROUTE_AUX_ZP_S12_PULSE
#define ROUTE_AUX_ZP_MG90S_TIME_MS 1000U
#define ROUTE_AUX_ZP_ID3_SERVO_ID 3U
#define ROUTE_TASK3_POST_ID3_TARGET_PULSE 700U
#define ROUTE_TASK3_POST_ID3_RESTORE_PULSE 980U
#define ROUTE_TASK3_POST_ID3_TIME_MS 400U
#define ROUTE_TASK3_POST_ID3_HOLD_MS 3000U
#define ROUTE_AUX_LEFT_SHIFT_DISTANCE_M 0.500f
#define ROUTE_AUX_ACK_TIMEOUT_MS 3000U
#define ROUTE_AUX_DONE_TIMEOUT_MS 5000U
#define ROUTE_AUX_RETRY_MS 200U


#define ROUTE_TRANSLATION_SPEED_M_S 1.400f
#define ROUTE_TRANSLATION_ACCEL_M_S2 0.500f
#define ROUTE_INITIAL_STRAFE_SPEED_M_S 1.400f
#define ROUTE_INITIAL_STRAFE_ACCEL_M_S2 0.500f
#define ROUTE_LONG_FORWARD_SPEED_M_S 1.400f
#define ROUTE_LONG_FORWARD_ACCEL_M_S2 0.500f
#define ROUTE_TRANSLATION_TIMEOUT_MS 15000U
#define DRIVE_STOP_TOLERANCE_M 0.004f
#define DRIVE_DISTANCE_SCALE 1.000f
/* FS-i6S forward stick produces negative vx on the verified chassis. */
#define ROUTE_FORWARD_SIGN -1.0f
/* Standard mecanum coordinates use negative vy and wz for rightward motion. */
#define ROUTE_RIGHT_STRAFE_SIGN 1.0f
#define ROUTE_RIGHT_TURN_SIGN 1.0f
#define ROUTE_LEFT_TURN_SIGN -1.0f
#define ROUTE_BACK_TURN_SIGN 1.0f

#define ROUTE_TURN_ANGLE_RAD 1.5707963f
#define ROUTE_STANDARD_QUARTER_TURN_RAD 1.5358897f /* 88 deg */
#define ROUTE_HALF_TURN_ANGLE_RAD 3.1415927f
#define ROUTE_GYRO_TURN_SCALE 1.0056f
#define ROUTE_TURN_MAX_SPEED_RAD_S 2.200f
#define ROUTE_TURN_ACCEL_RAD_S2 3.800f
#define ROUTE_TURN_KP 2.20f
#define ROUTE_TURN_KD 0.20f
#define ROUTE_TURN_TOLERANCE_RAD 0.020f
#define ROUTE_TURN_RATE_TOLERANCE_RAD_S 0.040f
#define ROUTE_TURN_SETTLE_MS 80U
#define ROUTE_TURN_TIMEOUT_MS 6000U
#define ROUTE_SEGMENT_SETTLE_MS 80U

/* RK arm task points. Directions and target colors mirror with the field:
 * BLUE uses right turns, left platform shifts, and blue/yellow disc targets;
 * RED uses left turns, right platform shifts, and red/yellow disc targets.
 * Platform targets are the two letters selected at task-two entry plus the
 * own-field ring; opponent-field rings and unselected letters are skipped. */
#define ROUTE_TASK1_DISC_CATCH_ENABLED 1U
#define ROUTE_TASK1_RK_ARM_TASK "DISC_CATCH"
#define ROUTE_TASK2_PLATFORM_PICK_ENABLED 1U
#define ROUTE_TASK2_RK_ARM_TASK "PLATFORM_PICK"
#define ROUTE_TASK2_PLATFORM_PICK_COUNT 8U
#define ROUTE_TASK2_PLATFORM_PRESELECT_COUNT 2U
#define ROUTE_TASK2_PLATFORM_SHIFT_1_M 0.100f
#define ROUTE_TASK2_PLATFORM_SHIFT_2_M 0.130f
#define ROUTE_TASK2_PLATFORM_SHIFT_3_M 0.100f
#define ROUTE_TASK2_PLATFORM_SHIFT_4_M 0.100f
#define ROUTE_TASK2_PLATFORM_SHIFT_5_M 0.100f
#define ROUTE_TASK2_PLATFORM_SHIFT_6_M 0.130f
#define ROUTE_TASK2_PLATFORM_SHIFT_7_M 0.100f
#define ROUTE_TASK3_COLUMN_CATCH_ENABLED 1U
#define ROUTE_TASK3_RK_ARM_TASK "COLUMN_CATCH"

#define RK_ARM_START_RETRY_MS 200U
#define RK_ARM_PROBE_ACK_TIMEOUT_MS 1800U
#define RK_ARM_ACK_TIMEOUT_MS 3000U
#define RK_ARM_BUSY_TIMEOUT_MS 12000U
#define RK_ARM_WAIT_FOREVER_FOR_ACK 0U
#define RK_ARM_TASK_TIMEOUT_MS 30000U
#define RK_ARM_DISC_CATCH_TASK_TIMEOUT_MS 60000U
#define RK_ARM_STATUS_PERIOD_MS 1000U
#define RK_ARM_STOP_TIMEOUT_MS 15000U
#define RK_ARM_REQUIRED 1U

/* Task-one commissioning gate: stop after DISC_CATCH completes and do not
 * enter the later task routes. */
#define ROUTE_TASK1_ONLY 0U
/* White-line commissioning gate: stop after the calibrated line pose so the
 * high-arm PREP_HIGH and line recognition can be inspected in isolation. */
#define ROUTE_STOP_AFTER_WHITE_LINE 0U

/* BMI088 yaw feedback parameters. */
#define GYRO_CALIBRATION_SAMPLES 120U
#define GYRO_CALIBRATION_PERIOD_MS 2U
#define GYRO_STATIONARY_STDDEV_MAX_RAD_S 0.050f
#define GYRO_Z_SIGN -1.0f
/* BMI088-to-chassis axis map.  Verify these four values from a ground-run log
 * if the controller board is mounted in a different orientation. */
#define IMU_ACCEL_BODY_X_INDEX 0U
#define IMU_ACCEL_BODY_Y_INDEX 1U
#define IMU_ACCEL_BODY_X_SIGN -1.0f
#define IMU_ACCEL_BODY_Y_SIGN -1.0f
#define IMU_ACCEL_FILTER_ALPHA 0.20f
#define IMU_ACCEL_DEADBAND_M_S2 0.08f
#define IMU_ACCEL_MAX_M_S2 4.00f
#define IMU_VELOCITY_PREDICTION_WEIGHT 0.08f
#define IMU_VELOCITY_MAX_ENCODER_DELTA_M_S 0.15f
#define IMU_ZERO_VELOCITY_THRESHOLD_M_S 0.020f
#define HEADING_KP 9.00f
#define HEADING_KD 0.30f
#define STRAFE_HEADING_KP 5.00f
#define STRAFE_HEADING_KD 0.25f
#define HEADING_MAX_CORRECTION_RAD_S 0.70f
#define HEADING_CORRECTION_SPEED_RATIO 0.65f
/* Keep each translation on its original world-frame line.  Heading control
 * alone can straighten the chassis after it has already drifted sideways. */
#define TRANSLATION_CROSS_TRACK_KP 2.40f
#define TRANSLATION_CROSS_TRACK_KD 0.22f
#define TRANSLATION_CROSS_TRACK_MAX_M_S 0.30f
#define TRANSLATION_FIELD_ORIENT_MAX_ERROR_RAD 0.12f
#define TRANSLATION_CROSS_TRACK_SETTLE_MAX_M_S 0.18f
#define TRANSLATION_CROSS_TRACK_TOLERANCE_M 0.008f
#define TRANSLATION_CROSS_SPEED_TOLERANCE_M_S 0.030f
#define TRANSLATION_CROSS_SETTLE_MS 60U
#define TRANSLATION_CROSS_SETTLE_TIMEOUT_MS 8000U
#define TRANSLATION_SETTLE_HEADING_MAX_CORRECTION_RAD_S 0.35f
/* Encoder odometry closes the along-track position loop; BMI088 gyro yaw
 * supplies the heading used to rotate wheel odometry into the route frame. */
#define ODOM_ALONG_POSITION_KP 1.20f
#define ODOM_ALONG_CORRECTION_MAX_M_S 0.25f
#define ODOM_ALONG_SPEED_KP 0.35f
#define ODOM_ALONG_SPEED_KI 0.80f
#define ODOM_ALONG_SPEED_INTEGRAL_MAX_M_S 0.25f
#define ODOM_ALONG_POSITION_TOLERANCE_M 0.008f
#define ODOM_ALONG_SPEED_TOLERANCE_M_S 0.030f
#define ODOM_ALONG_SETTLE_MS 60U

#define MOTOR_TX_DRAIN_TIMEOUT_MS 200U

/* FS-i6S receiver on P6 / UART5.  CH5 high takes over the chassis with RC;
 * when CH5 goes low or the receiver is lost, control returns to the start gate. */
#define ROUTE_RC_OVERRIDE_ENABLED 1U
#define IBUS_OVER_P6 1
#define SBUS_OVER_P6 2
#ifndef RC_PROTOCOL_MODE
#define RC_PROTOCOL_MODE SBUS_OVER_P6
#endif
#define RC_CH_VX_INDEX 1U
#define RC_CH_VY_INDEX 3U
#define RC_CH_WZ_INDEX 0U
#define RC_CH_UNLOCK_INDEX 4U
#define RC_CH_SPEED_INDEX 5U
#define RC_VX_DIRECTION 1.0f
#define RC_VY_DIRECTION 1.0f
#define RC_WZ_DIRECTION 1.0f
#define RC_CHANNEL_MIN_US 1000U
#define RC_CHANNEL_CENTER_US 1500U
#define RC_CHANNEL_MAX_US 2000U
#define RC_STICK_DEADZONE_US 80U
#define RC_ARM_CENTER_WINDOW_US 80U
#define RC_UNLOCK_LOW_MAX_US 1200U
#define RC_UNLOCK_HIGH_MIN_US 1800U
#define RC_SPEED_LOW_MAX_US 1200U
#define RC_SPEED_HIGH_MIN_US 1800U
#define RC_SPEED_LOW_SCALE 0.35f
#define RC_SPEED_MID_SCALE 0.65f
#define RC_SPEED_HIGH_SCALE 1.00f
#define RC_AXIS_EXPO 0.20f
#define RC_TIMEOUT_MS 300U
#define RC_OVERRIDE_ALLOW_HIGH_ON_BOOT 1U
#define RC_OVERRIDE_RELEASE_CONFIRM_MS 600U
/* A short RC/UART dropout is tolerated by replaying the last valid command.
 * A longer outage releases ownership and returns to the LCD start gate. */
#define RC_OVERRIDE_SIGNAL_LOSS_RELEASE_MS 1200U
#define RC_OVERRIDE_MAX_LINEAR_M_S 1.000f
#define RC_OVERRIDE_MAX_ANGULAR_RAD_S 2.000f
#define RC_OVERRIDE_WHEEL_RADIUS_M 0.050f
#define RC_OVERRIDE_HALF_LENGTH_M 0.180f
#define RC_OVERRIDE_HALF_WIDTH_M 0.160f
#define RC_OVERRIDE_WHEEL_FL_SIGN 1.0f
#define RC_OVERRIDE_WHEEL_FR_SIGN -1.0f
#define RC_OVERRIDE_WHEEL_RL_SIGN 1.0f
#define RC_OVERRIDE_WHEEL_RR_SIGN -1.0f

/* Fault handling already sends a zero and disables the motors on entry.
 * Reassert the safe state at a bounded rate while waiting for restart. */
#define ROUTE_FAULT_SAFE_REFRESH_MS 250U

/*
 * MG90S PWM outputs on the DM-MC-Board02 expansion header:
 * servo 0: PA0 / TIM2_CH1
 * servo 1: PA2 / TIM2_CH3
 * servo 2: PE9 / TIM1_CH1
 * servo 3: PE13 / TIM1_CH3
 */
#define SERVO_PWM_CHANNEL_COUNT 4U
#define SERVO_PWM_TIMER_HZ 1000000UL
#define SERVO_PWM_PERIOD_US 20000U
#define SERVO_MG90S_MIN_PULSE_US 500U
#define SERVO_MG90S_MAX_PULSE_US 2500U
#define SERVO_MG90S_MAX_ANGLE_DEG 180.0f
#define SERVO_MG90S_ROUTE_ANGLE_DEG 90.0f
#define SERVO_MG90S_PA0_INDEX 0U /* TIM2_CH1 */
#define SERVO_MG90S_PA2_INDEX 1U /* TIM2_CH3 */
#define SERVO_MG90S_POWER_ON_PA0_ANGLE_DEG 150.0f
#define SERVO_MG90S_POWER_ON_PA2_ANGLE_DEG 30.0f
#define SERVO_MG90S_POST_ROUTE_PA0_ANGLE_DEG 80.0f
#define SERVO_MG90S_POST_ROUTE_PA2_ANGLE_DEG 90.0f

#endif
