#include "stm32h7xx.h"

void ExitRun0Mode(void)
{
#if defined(USE_PWR_LDO_SUPPLY)
#if defined(SMPS)
    PWR->CR3 = (PWR->CR3 & ~PWR_CR3_SMPSEN) | PWR_CR3_LDOEN;
#else
    PWR->CR3 |= PWR_CR3_LDOEN;
#endif
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#elif defined(USE_PWR_EXTERNAL_SOURCE_SUPPLY)
#if defined(SMPS)
    PWR->CR3 = (PWR->CR3 & ~(PWR_CR3_SMPSEN | PWR_CR3_LDOEN)) | PWR_CR3_BYPASS;
#else
    PWR->CR3 = (PWR->CR3 & ~PWR_CR3_LDOEN) | PWR_CR3_BYPASS;
#endif
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#elif defined(USE_PWR_DIRECT_SMPS_SUPPLY) && defined(SMPS)
    PWR->CR3 &= ~PWR_CR3_LDOEN;
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#elif defined(USE_PWR_SMPS_1V8_SUPPLIES_LDO) && defined(SMPS)
    PWR->CR3 |= PWR_CR3_SMPSLEVEL_0 | PWR_CR3_SMPSEN | PWR_CR3_LDOEN;
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#elif defined(USE_PWR_SMPS_2V5_SUPPLIES_LDO) && defined(SMPS)
    PWR->CR3 |= PWR_CR3_SMPSLEVEL_1 | PWR_CR3_SMPSEN | PWR_CR3_LDOEN;
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#elif defined(USE_PWR_SMPS_1V8_SUPPLIES_EXT_AND_LDO) && defined(SMPS)
    PWR->CR3 |= PWR_CR3_SMPSLEVEL_0 | PWR_CR3_SMPSEXTHP | PWR_CR3_SMPSEN | PWR_CR3_LDOEN;
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#elif defined(USE_PWR_SMPS_2V5_SUPPLIES_EXT_AND_LDO) && defined(SMPS)
    PWR->CR3 |= PWR_CR3_SMPSLEVEL_1 | PWR_CR3_SMPSEXTHP | PWR_CR3_SMPSEN | PWR_CR3_LDOEN;
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#elif defined(USE_PWR_SMPS_1V8_SUPPLIES_EXT) && defined(SMPS)
    PWR->CR3 = (PWR->CR3 & ~PWR_CR3_LDOEN) | PWR_CR3_SMPSLEVEL_0 | PWR_CR3_SMPSEXTHP | PWR_CR3_SMPSEN | PWR_CR3_BYPASS;
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#elif defined(USE_PWR_SMPS_2V5_SUPPLIES_EXT) && defined(SMPS)
    PWR->CR3 = (PWR->CR3 & ~PWR_CR3_LDOEN) | PWR_CR3_SMPSLEVEL_1 | PWR_CR3_SMPSEXTHP | PWR_CR3_SMPSEN | PWR_CR3_BYPASS;
    while ((PWR->CSR1 & PWR_CSR1_ACTVOSRDY) == 0U) {}
#endif
}
